### ISSUE TITLE
Arc Progress Crash On Persian Language Apps 

### ISSUE THREAD

**Issue by sdarvish** [happydog-intj/CircleProgress#147]
When use arc progress in Persian language apps when use decimal formatter change number character and its make crash 

 Caused by: java.lang.NumberFormatException: For input string: "۷۰"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at com.github.lzyzsd.circleprogress.ArcProgress.setProgress(ArcProgress.java:191)
        at com.github.lzyzsd.circleprogress.ArcProgress.initByAttributes(ArcProgress.java:112)
        at com.github.lzyzsd.circleprogress.ArcProgress.<init>(ArcProgress.java:99)
        at com.github.lzyzsd.circleprogress.ArcProgress.<init>(ArcProgress.java:83)
        	... 61 more

**Comment by happydog-intj** [comment]
Fixed in v2.0.0 — replaced DecimalFormat with pure math rounding, eliminating the Persian/Arabic locale crash.
